version: "3.8"
services:
  toolbox-api:
    build: ./toolbox-api
    container_name: toolbox-api_c
    ports:
      - '3000:3000'
    volumes:
      - ./toolbox-api:/app
      - /app/node_modules
  toolbox-front:
    build: ./toolbox-front
    container_name: toolbox-front_c
    ports:
      - '3030:3030'
    volumes:
      - ./toolbox-front:/app
      - /app/node_modules
    stdin_open: true
    tty: true